# Generated by Django 5.2.6 on 2026-08-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='ip'),
        ),
    ]
