# Generated by Django 5.2.6 on 2026-05-23 06:24

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person account')),
            ],
            options={
                'verbose_name': 'OrganizationalUnit',
                'verbose_name_plural': 'OrganizationalUnits',
            },
            bases=('core.page', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='job_title')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person account')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizationalunit', verbose_name='organizational_unit')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
    ]
