# Generated by Django 5.2.6 on 2026-06-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('مدیر', 'مدیر'), ('باریستا', 'باریستا'), ('نگهبان', 'نگهبان'), ('کارگر', 'کارگر'), ('حسابدار', 'حسابدار')], max_length=100, verbose_name='job_title'),
        ),
    ]
