# Generated by Django 5.2.6 on 2026-06-09 00:50

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('app_name', models.CharField(blank=True, max_length=50, verbose_name='app_name')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='class_name')),
                ('short_description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیح کوتاه')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات کامل')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('meta_data', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='متادیتا')),
                ('priority', models.IntegerField(default=1000, verbose_name='ترتیب')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='core/images/page/thumbnail/', verbose_name='تصویر کوچک')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='core/images/page/header/', verbose_name='تصویر سربرگ')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.person', verbose_name='ثبت شده توسط')),
                ('locations', models.ManyToManyField(blank=True, to='attachments.location', verbose_name='locations')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='core.page', verbose_name='parent')),
                ('related_pages', models.ManyToManyField(blank=True, to='core.page', verbose_name='related_pages')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper, utility.models.ImageHelper),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('color_origin', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], max_length=50, null=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'EventCategory',
                'verbose_name_plural': 'دسته بندی رویداد ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('در جریان', 'در جریان'), ('آماده تحویل', 'آماده تحویل'), ('آماده ارسال', 'آماده ارسال'), ('در حال ارسال', 'در حال ارسال'), ('تایید شده', 'تایید شده'), ('تحویل شده', 'تحویل شده'), ('کنسل شده', 'کنسل شده'), ('برگشت از تحویل', 'برگشت از تحویل'), ('تایید نهایی شده', 'تایید نهایی شده'), ('پاس شده', 'پاس شده'), ('مانده حساب از قبل', 'مانده حساب از قبل')], default='پیش نویس', max_length=50, verbose_name='وضعیت')),
                ('event_datetime', models.DateTimeField(verbose_name='event_datetime')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='end_datetime')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eventcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'رویداد ها',
            },
            bases=('core.page', utility.models.DateTimeHelper),
        ),
    ]
