# Generated by Django 5.2.6 on 2026-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='color'),
        ),
    ]
