ACCOUNT_CODE_SEPERATOR1="/"
ACCOUNT_CODE_SEPERATOR="-"
CARD_NO_SEPERATOR="<small class=text-muted>.</small>"
ACCOUNT_NAME_SEPERATOR=" > "
EXCEL_PRODUCTS_DATA_START_ROW=3
EXCEL_SERVICES_DATA_START_ROW=3
EXCEL_ACCOUNTS_DATA_START_ROW=3