# Generated by Django 5.2.6 on 2026-05-23 06:24

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='warehouse/images/warehouse', verbose_name='thumbnail')),
                ('employees', models.ManyToManyField(blank=True, to='organization.employee', verbose_name='employees')),
                ('person_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'WareHouse',
                'verbose_name_plural': 'WareHouses',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.ImageHelper),
        ),
        migrations.CreateModel(
            name='ProductInWareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, verbose_name='unit_name')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product', verbose_name='product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'ProductInWareHouse',
                'verbose_name_plural': 'ProductInWareHouses',
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit_name', models.CharField(max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='unit_price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice', verbose_name='invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product', verbose_name='product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'MaterialRequests',
            },
        ),
        migrations.CreateModel(
            name='MaterialPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('مورد', 'مورد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('لیتر', 'لیتر'), ('میلی لیتر', 'میلی لیتر'), ('سی سی ', 'سی سی '), ('شل', 'شل'), ('سرویس', 'سرویس'), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('خشاب', 'خشاب'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('بشکه', 'بشکه'), ('گالن', 'گالن'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری'), ('جلد', 'جلد'), ('شیفت', 'شیفت'), ('روز', 'روز'), ('ماه', 'ماه'), ('سال', 'سال'), ('جلسه', 'جلسه')], default='عدد', max_length=100, verbose_name='unit_name')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_to', to='warehouse.warehouse', verbose_name='destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_from', to='warehouse.warehouse', verbose_name='source')),
            ],
            options={
                'verbose_name': 'MaterialPort',
                'verbose_name_plural': 'MaterialPorts',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='WareHouseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ورود', 'ورود'), ('خروج', 'خروج')], max_length=50, verbose_name='direction')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('shelf', models.CharField(blank=True, max_length=50, null=True, verbose_name='shelf')),
                ('row', models.CharField(blank=True, max_length=50, null=True, verbose_name='row')),
                ('col', models.CharField(blank=True, max_length=50, null=True, verbose_name='col')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], default='درخواست می شود', max_length=50, verbose_name='status')),
                ('type', models.CharField(choices=[('فروش', 'فروش'), ('خرید', 'خرید'), ('انتقال', 'انتقال'), ('نامشخص', 'نامشخص')], default='نامشخص', max_length=50, verbose_name='type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.employee', verbose_name='employee')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoiceline', verbose_name='invoice_line')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationalunit', verbose_name='organizational_unit')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'WareHouseSheet',
                'verbose_name_plural': 'WareHouseSheets',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='WareHouseSheetLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('lot_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='lot_no')),
                ('barcode_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_1')),
                ('barcode_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_2')),
                ('barcode_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='barcode_3')),
                ('label_origin', models.ImageField(blank=True, null=True, upload_to='warehouse/images/label', verbose_name='label_origin')),
                ('production_date', models.DateTimeField(blank=True, null=True, verbose_name='production_date')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='expiration_date')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('warehouse_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousesheet', verbose_name='warehouse_sheet')),
            ],
            options={
                'verbose_name': 'WareHouseSheetLabel',
                'verbose_name_plural': 'WareHouseSheetLabels',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='WareHouseSheetSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('درخواست می شود', 'درخواست می شود'), ('تایید می شود', 'تایید می شود'), ('رد می شود', 'رد می شود'), ('بررسی می شود', 'بررسی می شود')], max_length=50, verbose_name='status')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.employee', verbose_name='employee')),
                ('warehouse_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousesheet', verbose_name='warehouse_sheet')),
            ],
            options={
                'verbose_name': 'WareHouseSheetSignature',
                'verbose_name_plural': 'WareHouseSheetSignatures',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
    ]
