# Generated by Django 5.2.6 on 2026-06-09 00:50

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account')),
                ('regions', models.ManyToManyField(to='utility.region', verbose_name='regions')),
            ],
            options={
                'verbose_name': 'MarketPerson',
                'verbose_name_plural': 'MarketPersons',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
            ],
            options={
                'verbose_name': 'CustomerGroup',
                'verbose_name_plural': 'CustomerGroups',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='code')),
                ('colour', models.CharField(blank=True, max_length=50, null=True, verbose_name='color')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='weight')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='volume')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='dimensions')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
            bases=('core.page', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
                ('grade', models.CharField(choices=[('جدید', 'جدید'), ('با سابقه', 'با سابقه'), ('تایید شده', 'تایید شده')], default='جدید', max_length=50, verbose_name='grade')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('مورد', 'مورد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('لیتر', 'لیتر'), ('میلی لیتر', 'میلی لیتر'), ('سی سی ', 'سی سی '), ('شل', 'شل'), ('سرویس', 'سرویس'), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('خشاب', 'خشاب'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('بشکه', 'بشکه'), ('گالن', 'گالن'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری'), ('جلد', 'جلد'), ('شیفت', 'شیفت'), ('روز', 'روز'), ('ماه', 'ماه'), ('سال', 'سال'), ('جلسه', 'جلسه')], max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('available', models.IntegerField(verbose_name='available')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت ')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customergroup', verbose_name='group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.region', verbose_name='region')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('marketperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.marketperson')),
                ('groups', models.ManyToManyField(blank=True, to='market.customergroup', verbose_name='customer groups')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('market.marketperson',),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(blank=True, default=1, verbose_name='ردیف')),
                ('quantity', models.IntegerField(default=0, verbose_name='تعداد')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیحات')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.shop', verbose_name='فروش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'CartItem',
                'verbose_name_plural': 'CartItems',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
                ('destination', models.CharField(max_length=200, verbose_name='destination')),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverer_set', to='authentication.person', verbose_name='deliverer')),
                ('packages', models.ManyToManyField(to='market.package', verbose_name='packages')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_set', to='authentication.person', verbose_name='recipient')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.shipper', verbose_name='shipper')),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
            },
            bases=('accounting.financialevent', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ShopPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع ')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان ')),
                ('quantity', models.IntegerField(verbose_name='تعداد کل')),
                ('available', models.IntegerField(verbose_name='موجود')),
                ('shops', models.ManyToManyField(to='market.shop', verbose_name='shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'ShopPackage',
                'verbose_name_plural': 'ShopPackages',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.AddField(
            model_name='shipper',
            name='suppliers',
            field=models.ManyToManyField(to='market.supplier', verbose_name='suppliers'),
        ),
    ]
