# Generated by Django 5.2.6 on 2026-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='grade',
            field=models.CharField(choices=[('جدید', 'جدید'), ('با سابقه', 'با سابقه'), ('تایید شده', 'تایید شده')], default='جدید', max_length=50, verbose_name='grade'),
        ),
    ]
