# Generated by Django 5.2.6 on 2026-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='coef',
            field=models.IntegerField(default=1, verbose_name='coef'),
        ),
    ]
