# Generated by Django 5.2.6 on 2026-05-31 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('utility', '0002_city_state_region_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketperson',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.region', verbose_name='region'),
            preserve_default=False,
        ),
    ]
