# Generated by Django 5.2.6 on 2026-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_shop_coef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='unit_name',
            field=models.CharField(max_length=50, verbose_name='unit_name'),
        ),
    ]
