# Generated by Django 5.2.6 on 2026-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketperson_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
