# Generated by Django 5.2.6 on 2026-05-21 13:49

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('url', models.CharField(blank=True, max_length=50000, null=True, verbose_name='url')),
                ('description', models.CharField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('app_name', models.CharField(blank=True, choices=[('projectmanager', 'projectmanager'), ('accounting', 'accounting'), ('web', 'web'), ('transport', 'transport'), ('log', 'log'), ('map', 'map'), ('market', 'market'), ('stock', 'stock'), ('authentication', 'authentication'), ('dashboard', 'dashboard'), ('polls', 'polls')], max_length=50, null=True, verbose_name='app_name')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
    ]
