# Generated by Django 5.2.6 on 2026-06-09 00:50

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ما', max_length=50, verbose_name='title')),
                ('about', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='about')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUss',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('for_home', models.BooleanField(default=False, verbose_name='for home')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end_date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='address')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='location')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUss',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_origin', models.ImageField(upload_to='blog/images/Banner/', verbose_name='تصویر اسلایدر  1333*2000 ')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, max_length=2000, null=True, verbose_name='بدنه')),
                ('text_color', models.CharField(default='#fff', max_length=20, verbose_name='رنگ متن')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('tag_number', models.IntegerField(default=100, verbose_name='عدد برچسب')),
                ('tag_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن برچسب')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'HomeSliders',
            },
            bases=(models.Model, utility.models.ImageHelper, utility.models.LinkHelper),
        ),
    ]
