# Generated by Django 5.2.6 on 2026-05-31 07:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='about')),
            ],
            options={
                'verbose_name': 'AboutUs',
                'verbose_name_plural': 'AboutUss',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobile')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='address')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='location')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUss',
            },
        ),
    ]
