# Generated by Django 5.2.6 on 2026-05-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_date'),
        ),
    ]
