# Generated by Django 5.2.6 on 2026-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutus_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='درباره ما', max_length=50, verbose_name='title'),
        ),
    ]
