# Generated by Django 5.2.6 on 2026-05-25 15:27

import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_origin', models.ImageField(upload_to='blog/images/Banner/', verbose_name='تصویر اسلایدر  1333*2000 ')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, max_length=2000, null=True, verbose_name='بدنه')),
                ('text_color', models.CharField(default='#fff', max_length=20, verbose_name='رنگ متن')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('tag_number', models.IntegerField(default=100, verbose_name='عدد برچسب')),
                ('tag_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن برچسب')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'HomeSliders',
            },
            bases=(models.Model, utility.models.ImageHelper, utility.models.LinkHelper),
        ),
    ]
