# Generated by Django 5.2.6 on 2026-05-23 06:24

import django.core.files.storage
import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('active_directory', models.CharField(blank=True, max_length=100, null=True, verbose_name='active_directory')),
                ('work_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='work_group')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System (os)')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='url')),
                ('local_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='local_ip')),
                ('remote_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='remote_ip')),
                ('any_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_address')),
                ('any_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='any_desk_password')),
                ('dorsan_desk_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_address')),
                ('dorsan_desk_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='dorsan_desk_password')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='model name')),
                ('id_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='id_name')),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='mac_address')),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='serial_no')),
                ('pattern', models.CharField(blank=True, max_length=50, null=True, verbose_name='pattern')),
                ('part_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='part_no')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='password')),
                ('identity', models.CharField(blank=True, max_length=50, null=True, verbose_name='identity')),
                ('wireless_mode', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_mode')),
                ('wireless_band', models.CharField(blank=True, max_length=50, null=True, verbose_name='wireless_band')),
                ('ssid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ssid')),
                ('preshared_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='preshared_key')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='frequency')),
                ('protocol', models.CharField(blank=True, max_length=50, null=True, verbose_name='protocol')),
                ('channel_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='channel_width')),
                ('adsl_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_username')),
                ('adsl_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='adsl_password')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='telephone')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.brand', verbose_name='brand')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'RemoteClient',
                'verbose_name_plural': 'RemoteClients',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('type', models.CharField(choices=[('تایپ A', 'تایپ A'), ('تایپ B', 'تایپ B')], default='تایپ A', max_length=50, verbose_name='تایپ')),
                ('percentage_completed', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('weight', models.IntegerField(default=1, verbose_name='وزن پروژه')),
                ('amount', models.IntegerField(default=0, verbose_name='ارزش پروژه')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contracted', to='organization.organizationalunit', verbose_name='contractor')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_employed', to='organization.organizationalunit', verbose_name='employer')),
                ('events', models.ManyToManyField(blank=True, related_name='project_events', to='core.event', verbose_name='events')),
                ('invoices', models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoices')),
                ('remote_clients', models.ManyToManyField(blank=True, to='projectmanager.remoteclient', verbose_name='remote_clients')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('core.event', utility.models.LinkHelper, utility.models.DateHelper),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('type', models.CharField(choices=[('تایپ A', 'تایپ A'), ('تایپ B', 'تایپ B'), ('تایپ C', 'تایپ C')], max_length=50, verbose_name='تایپ')),
                ('status', models.CharField(choices=[('شروع شده', 'شروع شده'), ('در جریان', 'در جریان'), ('پایان یافته', 'پایان یافته')], default='شروع شده', max_length=50, verbose_name='وضعیت')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='d:\\private_html\\phoenix12\\upload'), upload_to='projectmanager/ticket-files', verbose_name='فایل ضمیمه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ticket', verbose_name='parent')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='شخص')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
            bases=(models.Model, utility.models.DateTimeHelper, utility.models.LinkHelper),
        ),
    ]
