# Generated by Django 5.2.6 on 2026-06-27 02:37

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_person_prefix'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('تعریف اولیه', 'تعریف اولیه'), ('برنامه ریزی شده', 'برنامه ریزی شده'), ('برنامه ریزی نشده', 'برنامه ریزی نشده'), ('پایان یافته', 'پایان یافته')], default='تعریف اولیه', max_length=50, verbose_name='status')),
                ('percentage_completed', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='end_datetime')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
    ]
