# Generated by Django 5.2.6 on 2026-06-09 00:50

import django.db.models.deletion
import utility.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس'), (' مجتمع', ' مجتمع'), ('فروشگاه', 'فروشگاه'), ('دانشگاه', 'دانشگاه'), ('رستوران', 'رستوران'), ('آموزشگاه', 'آموزشگاه'), ('اداره', 'اداره')], default='آقای', max_length=50, verbose_name='پیشوند')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('bio', models.CharField(blank=True, max_length=50, null=True, verbose_name='بیو')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='full_name')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='authentication/images/person/', verbose_name='تصویر')),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('هردو', 'هردو'), ('هیچکدام', 'هیچکدام'), ('مستقل', 'مستقل'), ('دیگر', 'دیگر')], default='مرد', max_length=50, verbose_name='جنسیت')),
                ('type', models.CharField(choices=[('مشتری', 'مشتری'), ('حقوقی', 'حقوقی'), ('حقیقی', 'حقیقی'), ('پرسنل', 'پرسنل'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت')),
                ('type2', models.CharField(choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], default='حقیقی', max_length=50, verbose_name='نوع')),
                ('economic_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اقتصادی')),
                ('melli_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='موبایل')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='تاریخ تولد')),
                ('birth_location', models.CharField(blank=True, max_length=20, null=True, verbose_name='محل تولد')),
                ('father_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='نام پدر')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
            bases=(models.Model, utility.models.ImageHelper, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='url')),
                ('url', models.CharField(max_length=2000, verbose_name='url')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'MyLink',
                'verbose_name_plural': 'MyLinks',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ClipBoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('text', models.CharField(max_length=100, verbose_name='text')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'ClipBoardItem',
                'verbose_name_plural': 'ClipBoardItems',
            },
        ),
    ]
