# Generated by Django 5.2.6 on 2026-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, choices=[('آقای', 'آقای'), ('خانم', 'خانم'), ('شرکت', 'شرکت'), ('دکتر', 'دکتر'), ('مهندس', 'مهندس'), (' مجتمع', ' مجتمع'), ('فروشگاه', 'فروشگاه'), ('دانشگاه', 'دانشگاه'), ('رستوران', 'رستوران'), ('آموزشگاه', 'آموزشگاه'), ('اداره', 'اداره')], max_length=50, null=True, verbose_name='پیشوند'),
        ),
    ]
