# Generated by Django 5.2.6 on 2026-09-16 02:35

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_alter_asset_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.product')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
            bases=('accounting.product', utility.models.LinkHelper),
        ),
    ]
