# Generated by Django 5.2.6 on 2026-05-21 13:49

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='messenger/images/channel/', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('channel_name', models.CharField(max_length=20, verbose_name='channel_name')),
                ('app_id', models.CharField(max_length=20, verbose_name='app_id')),
                ('key', models.CharField(max_length=50, verbose_name='key')),
                ('secret', models.CharField(max_length=50, verbose_name='secret')),
                ('cluster', models.CharField(default='us2', max_length=20, verbose_name='cluster')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('body', tinymce.models.HTMLField(verbose_name='body')),
                ('event', models.CharField(max_length=50, verbose_name='event')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='date send')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channel', verbose_name='channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='DEFAULT', max_length=50, verbose_name='event')),
                ('date_join', models.DateTimeField(verbose_name='date join')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.channel', verbose_name='channel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.message')),
                ('read', models.BooleanField(default=False, verbose_name='read')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
            bases=('messenger.message', utility.models.LinkHelper),
        ),
    ]
