# Generated by Django 5.2.6 on 2026-06-09 00:50

import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('area', models.CharField(blank=True, max_length=1000, null=True, verbose_name='area')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', tinymce.models.HTMLField(verbose_name='comment')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
            bases=(models.Model, utility.models.DateTimeHelper, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='title')),
                ('icon_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='icon fa')),
                ('icon_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='material_icon')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='svg_icon')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('muted', 'muted'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('rose', 'rose'), ('dark', 'dark')], default='primary', max_length=50, verbose_name='color')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض آیکون')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع آیکون')),
                ('priority', models.IntegerField(default=1000, verbose_name='priority')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/Icon/', verbose_name='تصویر آیکون')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=50000, null=True, verbose_name='توضیحات')),
                ('priority', models.IntegerField(default=1000, verbose_name='priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Thumbnail/', verbose_name='تصویر کوچک')),
                ('image_main_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Main/', verbose_name='تصویر اصلی')),
                ('image_header_origin', models.ImageField(blank=True, null=True, upload_to='attachments/images/ImageBase/Header/', verbose_name='تصویر سربرگ')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'تصاویر',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='datetime_added')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نقطه')),
                ('location', models.CharField(max_length=1000, verbose_name='لوکیشن')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='longitude')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
            ],
            options={
                'verbose_name': 'لوکیشن',
                'verbose_name_plural': 'لوکیشن ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='PagePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('type', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('رسمی', 'رسمی')], default='پیش نویس', max_length=50, verbose_name='type')),
                ('printed', models.BooleanField(default=False, verbose_name='printed')),
            ],
            options={
                'verbose_name': 'PagePrint',
                'verbose_name_plural': 'PagePrints',
            },
            bases=(models.Model, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
