# Generated by Django 5.2.6 on 2026-09-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_area_page'),
        ('core', '0002_alter_page_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='page'),
        ),
    ]
