# Generated by Django 5.2.6 on 2026-06-09 00:50

import accounting.models
import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='code')),
                ('type', models.CharField(choices=[('گروه', 'گروه'), ('کل', 'کل'), ('معین 1', 'معین 1'), ('معین 2', 'معین 2'), ('تفصیلی 1', 'تفصیلی 1'), ('تفصیلی 2', 'تفصیلی 2'), ('تفصیلی 3', 'تفصیلی 3'), ('تفصیلی 4', 'تفصیلی 4'), ('تفصیلی 5', 'تفصیلی 5'), ('تفصیلی 6', 'تفصیلی 6')], max_length=50, verbose_name='نوع')),
                ('nature', models.CharField(choices=[('بستانکار', 'بستانکار'), ('فقط بستانکار', 'فقط بستانکار'), ('بدهکار', 'بدهکار'), ('فقط بدهکار', 'فقط بدهکار'), ('بدون کنترل', 'بدون کنترل')], default='بدون کنترل', max_length=50, verbose_name='ماهیت')),
                ('level', models.IntegerField(verbose_name='level')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='bedehkar')),
                ('bestankar', models.IntegerField(default=0, verbose_name='bestankar')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
            },
            bases=('core.page', utility.models.LinkHelper, accounting.models.PersonAccountHelper),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='branch')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='tel')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('logo_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/brand', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.ImageHelper),
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('payment_method', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('همراه بانک', 'همراه بانک'), ('فروش کالا', 'فروش کالا'), ('فروش خدمات', 'فروش خدمات'), ('نقدی', 'نقدی'), ('چک', 'چک'), ('کارتخوان', 'کارتخوان'), ('فیش بانکی', 'فیش بانکی'), ('کارت به کارت', 'کارت به کارت')], default='پیش نویس', max_length=50, verbose_name='نوع پرداخت')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('tax_percentage', models.IntegerField(default=0, verbose_name='درصد مالیات')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='مالیات')),
                ('discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='هزینه حمل')),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='postal_code')),
                ('bedehkar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bedehkar_events', to='accounting.account', verbose_name='دریافت کننده')),
                ('bestankar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bestankar_events', to='accounting.account', verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'رویداد مالی',
                'verbose_name_plural': 'Financial Events',
            },
            bases=('core.event', utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='date_time')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date_modified ')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('رد شده', 'رد شده'), ('تایید شده', 'تایید شده')], default='پیش نویس', max_length=20, verbose_name='status')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='بدهکار')),
                ('bestankar', models.IntegerField(default=0, verbose_name='بستانکار')),
                ('balance', models.IntegerField(default=0, verbose_name='تراز')),
            ],
            options={
                'verbose_name': 'سند مالی',
                'verbose_name_plural': 'سند های مالی',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('معلق', 'معلق'), ('بسته شده', 'بسته شده'), ('در جریان', 'در جریان'), ('پیش نویس', 'پیش نویس'), ('موقتی', 'موقتی')], default='معلق', max_length=20, verbose_name='status')),
                ('in_progress', models.BooleanField(default=False, verbose_name='in progress')),
            ],
            options={
                'verbose_name': 'سال مالی',
                'verbose_name_plural': 'سال های مالی',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
            ],
            options={
                'verbose_name': 'InvoiceLineItem',
                'verbose_name_plural': 'موارد قابل فروش',
            },
            bases=('core.page', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/cheque/', verbose_name='تصویر')),
            ],
            bases=('accounting.financialevent', utility.models.ImageHelper),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('financialevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.financialevent')),
                ('invoice_no', models.IntegerField(default=0, verbose_name='invoice_no')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
            bases=('accounting.financialevent',),
        ),
        migrations.CreateModel(
            name='FinancialDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date_modified ')),
                ('bedehkar', models.IntegerField(default=0, verbose_name='بدهکار')),
                ('bestankar', models.IntegerField(default=0, verbose_name='بستانکار')),
                ('balance', models.IntegerField(default=0, verbose_name='بالانس')),
                ('status', models.CharField(choices=[('پیش نویس', 'پیش نویس'), ('رد شده', 'رد شده'), ('تایید شده', 'تایید شده')], default='پیش نویس', max_length=50, verbose_name='status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account')),
                ('financial_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.financialdocument', verbose_name='accountingdocument')),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.financialevent', verbose_name='event')),
            ],
            options={
                'verbose_name': 'سطر سند حسابداری',
                'verbose_name_plural': 'سطر های سند حسابداری',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.financialyear', verbose_name='سال مالی'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('invoicelineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoicelineitem')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='model')),
                ('barcode', models.CharField(blank=True, max_length=500, null=True, verbose_name='barcode')),
                ('rop', models.IntegerField(default=0, verbose_name='نقطه سفارش مجدد')),
                ('unit_name', models.CharField(default='عدد', max_length=500, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(default=0, verbose_name='unit_price')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.brand', verbose_name='brand')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا ها',
            },
            bases=('accounting.invoicelineitem',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('invoicelineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoicelineitem')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'خدمات',
            },
            bases=('accounting.invoicelineitem',),
        ),
        migrations.CreateModel(
            name='InvoiceLineItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('مورد', 'مورد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('لیتر', 'لیتر'), ('میلی لیتر', 'میلی لیتر'), ('سی سی ', 'سی سی '), ('شل', 'شل'), ('سرویس', 'سرویس'), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('خشاب', 'خشاب'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('بشکه', 'بشکه'), ('گالن', 'گالن'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری'), ('جلد', 'جلد'), ('شیفت', 'شیفت'), ('روز', 'روز'), ('ماه', 'ماه'), ('سال', 'سال'), ('جلسه', 'جلسه')], max_length=50, verbose_name='unit_name')),
                ('coef', models.FloatField(default=1, verbose_name='coef')),
                ('unit_price', models.IntegerField(default=1, verbose_name='unit_price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounting.invoicelineitem', verbose_name='invoicelineitem')),
            ],
            options={
                'verbose_name': 'InvoiceLineItemUnit',
                'verbose_name_plural': 'واحد های قابل فروش',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.DateTimeHelper),
        ),
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('پیش فرض', 'پیش فرض'), ('مشتری', 'مشتری'), ('فروشنده', 'فروشنده'), ('پرسنل', 'پرسنل'), ('سهامدار', 'سهامدار'), ('پیمانکار', 'پیمانکار'), ('کارفرما', 'کارفرما'), ('هزینه', 'هزینه')], default='پیش فرض', max_length=50, verbose_name='title')),
                ('code_length', models.IntegerField(default=5, verbose_name='code_length')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'دسته بندی اشخاص',
                'verbose_name_plural': 'دسته بندی های اشخاص',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('card_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='card_no')),
                ('shaba_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='shaba_no')),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='account_no')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bank', verbose_name='bank')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب های بانکی',
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='PersonAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person')),
                ('person_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personcategory', verbose_name='person_category')),
            ],
            options={
                'verbose_name': 'PersonAccount',
                'verbose_name_plural': 'حساب های اشخاص',
            },
            bases=('accounting.account', utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.personaccount', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'دارایی',
                'verbose_name_plural': 'دارایی ها',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0, verbose_name='row')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit_name', models.CharField(choices=[('عدد', 'عدد'), ('مورد', 'مورد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', 'گرم'), ('متر', 'متر'), ('متر مربع', 'متر مربع'), ('متر مکعب', 'متر مکعب'), ('لیتر', 'لیتر'), ('میلی لیتر', 'میلی لیتر'), ('سی سی ', 'سی سی '), ('شل', 'شل'), ('سرویس', 'سرویس'), ('شاخه', 'شاخه'), ('نود شبکه', 'نود شبکه'), ('شیشه', 'شیشه'), ('دستگاه', 'دستگاه'), ('ورق', 'ورق'), ('تن', 'تن'), ('خط', 'خط'), ('پورس', 'پورس'), ('قطعه', 'قطعه'), ('رول', 'رول'), ('تخته', 'تخته'), ('لینک', 'لینک'), ('خشاب', 'خشاب'), ('نفر', 'نفر'), ('بسته', 'بسته'), ('کیسه', 'کیسه'), ('شات', 'شات'), ('ست', 'ست'), ('فنجان', 'فنجان'), ('جفت', 'جفت'), ('دست', 'دست'), ('بشکه', 'بشکه'), ('گالن', 'گالن'), ('کارتن', 'کارتن'), ('ساعت', 'ساعت'), ('دقیقه', 'دقیقه'), ('جعبه', 'جعبه'), ('سبد', 'سبد'), ('راس', 'راس'), ('بطری', 'بطری'), ('جلد', 'جلد'), ('شیفت', 'شیفت'), ('روز', 'روز'), ('ماه', 'ماه'), ('سال', 'سال'), ('جلسه', 'جلسه')], max_length=50, verbose_name='unit_name')),
                ('unit_price', models.IntegerField(verbose_name='unit_price')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='discount_percentage')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='tax_amount')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='description')),
                ('status', models.CharField(blank=True, choices=[('نو', 'نو'), ('کارکرده', 'کارکرده'), ('کارکرده در حد نو', 'کارکرده در حد نو'), ('نو بدون جعبه', 'نو بدون جعبه'), ('تعمیر شده', 'تعمیر شده'), ('خراب', 'خراب'), ('داغون', 'داغون'), ('قلابی', 'قلابی'), ('اصلی', 'اصلی')], max_length=5000, null=True, verbose_name='status')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.person', verbose_name='person')),
                ('invoice_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoicelineitem', verbose_name='invoice_line_item')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'InvoiceLine',
                'verbose_name_plural': 'سطر های فاکتور ها',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'ProductSpecification',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('priority', models.IntegerField(default=100, verbose_name='priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/category/thumbnail/', verbose_name='تصویر کوچک')),
                ('header_origin', models.ImageField(blank=True, null=True, upload_to='accounting/images/category/header/', verbose_name='تصویر سربرگ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.category', verbose_name='parent')),
                ('products', models.ManyToManyField(blank=True, to='accounting.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
            bases=(models.Model, utility.models.LinkHelper, utility.models.ImageHelper),
        ),
    ]
