# Generated by Django 5.2.6 on 2026-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='postal_code'),
        ),
    ]
