# Generated by Django 5.2.6 on 2026-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
