# Generated by Django 5.2.6 on 2026-06-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.productspecification', verbose_name='parent'),
        ),
    ]
