# Generated by Django 5.2.6 on 2026-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_asset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='variz_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='variz_info'),
        ),
    ]
