# Generated by Django 5.2.17 on 2026-09-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_asset_owner'),
        ('authentication', '0002_alter_person_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaccount',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.person', verbose_name='person'),
        ),
    ]
