# Generated by Django 5.2.6 on 2026-10-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_personaccount_person'),
        ('accounting', '0005_invoice_variz_info'),
    ]

    operations = [
    ]
