# Generated by Django 5.2.6 on 2026-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_merge_20261001_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
    ]
