# Generated by Django 5.2.6 on 2026-06-10 21:40

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_asset_price'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.asset')),
                ('vehicle_type', models.CharField(choices=[('موتورسیکلت', 'موتورسیکلت'), ('وانت', 'وانت'), ('سواری', 'سواری'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('گریدر', 'گریدر'), ('لودر', 'لودر'), ('تریلی', 'تریلی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور'), ('خاور', 'خاور')], default='سواری', max_length=50, verbose_name='نوع وسیله ')),
                ('brand_name', models.CharField(choices=[('تویوتا', 'تویوتا'), ('پژو', 'پژو'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('پیشتاز', 'پیشتاز'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('داف', 'داف'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='ایران خودرو', max_length=50, verbose_name='برند')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('plaque', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('driver', models.CharField(blank=True, max_length=50, null=True, verbose_name='راننده')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='سال')),
                ('vehicle_color', models.CharField(choices=[('سفید', 'سفید'), ('سیاه', 'سیاه'), ('نوک مدادی', 'نوک مدادی'), ('دلفینی', 'دلفینی'), ('بژ', 'بژ'), ('قرمز', 'قرمز')], default='سفید', max_length=50, verbose_name='رنگ')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
            bases=('accounting.asset',),
        ),
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'ServiceMan',
                'verbose_name_plural': 'ServiceMans',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='MaintenanceInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.serviceman', verbose_name='service man')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'MaintenanceInvoice',
                'verbose_name_plural': 'MaintenanceInvoices',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
                ('invoices', models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoice')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.serviceman', verbose_name='service man')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
            bases=('core.event',),
        ),
    ]
