# Generated by Django 5.2.6 on 2026-08-25 19:40

import django.db.models.deletion
import tinymce.models
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_alter_asset_owner'),
        ('attachments', '0003_alter_area_page'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='project_name')),
                ('area_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='area_name')),
                ('vehicle_event_type', models.CharField(max_length=50, verbose_name='vehicle_event_type')),
            ],
            options={
                'verbose_name': 'VehicleEvent',
                'verbose_name_plural': 'VehicleEvents',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.asset')),
                ('vehicle_type', models.CharField(choices=[('لودر', 'لودر'), ('بیل مکانیکی', 'بیل مکانیکی'), ('کمپرسی', 'کمپرسی'), ('گریدر', 'گریدر'), ('بلدوزر', 'بلدوزر'), ('تریلی', 'تریلی'), ('خاور', 'خاور'), ('وانت', 'وانت'), ('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='سواری', max_length=50, verbose_name='نوع وسیله ')),
                ('vehicle_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد وسیله ')),
                ('brand_name', models.CharField(choices=[('تویوتا', 'تویوتا'), ('پژو', 'پژو'), ('بنز', 'بنز'), ('ایسوزو', 'ایسوزو'), ('اسکانیا', 'اسکانیا'), ('مزدا', 'مزدا'), ('ولوو', 'ولوو'), ('پیشتاز', 'پیشتاز'), ('کاترپیلار', 'کاترپیلار'), ('هیوندای', 'هیوندای'), ('هووو', 'هووو'), ('دانگ فنگ', 'دانگ فنگ'), ('سایپا', 'سایپا'), ('داف', 'داف'), ('ایران خودرو', 'ایران خودرو'), ('XCMG', 'XCMG')], default='ایران خودرو', max_length=50, verbose_name='برند')),
                ('model_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('plaque', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('driver', models.CharField(blank=True, max_length=50, null=True, verbose_name='راننده')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='سال')),
                ('vehicle_color', models.CharField(choices=[('سفید', 'سفید'), ('سیاه', 'سیاه'), ('نوک مدادی', 'نوک مدادی'), ('دلفینی', 'دلفینی'), ('بژ', 'بژ'), ('قرمز', 'قرمز')], default='سفید', max_length=50, verbose_name='رنگ')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
            bases=('accounting.asset',),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Karkerd',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicleevent')),
                ('start_hour', models.FloatField(verbose_name='ساعت شروع')),
                ('end_hour', models.FloatField(verbose_name='ساعت پایان')),
                ('start_kilometer', models.IntegerField(blank=True, null=True, verbose_name='کیلومتر شروع')),
                ('end_kilometer', models.IntegerField(blank=True, null=True, verbose_name='کیلومتر پایان')),
                ('load', models.CharField(blank=True, max_length=50, null=True, verbose_name='load')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
            ],
            options={
                'verbose_name': 'Karkerd',
                'verbose_name_plural': 'Karkerds',
            },
            bases=('transport.vehicleevent',),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver', verbose_name='driver'),
        ),
        migrations.CreateModel(
            name='ServiceMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'ServiceMan',
                'verbose_name_plural': 'ServiceMans',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.invoice')),
                ('hour', models.IntegerField(default=0, verbose_name='hour')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.serviceman', verbose_name='service man')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'MaintenanceInvoice',
                'verbose_name_plural': 'MaintenanceInvoices',
            },
            bases=('accounting.invoice',),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('maintenance_type', models.CharField(choices=[('شستشو', 'شستشو'), ('سوخت', 'سوخت'), ('تعمیر موتور', 'تعمیر موتور'), ('بیمه', 'بیمه'), ('برق خودرو', 'برق خودرو'), ('لاستیک', 'لاستیک'), ('بدنه', 'بدنه'), ('جلوبندی', 'جلوبندی'), ('تعویض روغن', 'تعویض روغن')], max_length=100, verbose_name='سرویس')),
                ('hour', models.IntegerField(default=0, verbose_name='hour')),
                ('kilometer', models.IntegerField(default=0, verbose_name='کیلومتر')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.driver', verbose_name='driver')),
                ('invoices', models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoice')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.serviceman', verbose_name='service man')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_datetime', models.DateTimeField(verbose_name='status_datetime')),
                ('kilometer', models.IntegerField(verbose_name='kilometer')),
                ('hour', models.IntegerField(verbose_name='hour')),
                ('motor', models.CharField(blank=True, max_length=500, null=True, verbose_name='motor')),
                ('gear_box', models.CharField(blank=True, max_length=500, null=True, verbose_name='gear_box')),
                ('ziroband', models.CharField(blank=True, max_length=500, null=True, verbose_name='ziroband')),
                ('cabin', models.CharField(blank=True, max_length=500, null=True, verbose_name='cabin')),
                ('cooler', models.CharField(blank=True, max_length=500, null=True, verbose_name='cooler')),
                ('heater', models.CharField(blank=True, max_length=500, null=True, verbose_name='heater')),
                ('wiring', models.CharField(blank=True, max_length=500, null=True, verbose_name='wiring')),
                ('light', models.CharField(blank=True, max_length=500, null=True, verbose_name='light')),
                ('hydrolic', models.CharField(blank=True, max_length=500, null=True, verbose_name='hydrolic')),
                ('pakat', models.CharField(blank=True, max_length=500, null=True, verbose_name='pakat')),
                ('compress', models.CharField(blank=True, max_length=500, null=True, verbose_name='compress')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیحات کامل')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.location', verbose_name='location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'VehicleStatus',
                'verbose_name_plural': 'VehicleStatuses',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='shift_date')),
                ('shift', models.CharField(max_length=50, verbose_name='shift')),
                ('start_hour', models.IntegerField(default=0, verbose_name='start_hour')),
                ('end_hour', models.IntegerField(default=0, verbose_name='end_hour')),
                ('vehicle_start_hour', models.FloatField(default=0, verbose_name='vehicle_start_hour')),
                ('vehicle_end_hour', models.FloatField(default=0, verbose_name='vehicle_end_hour')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('bar', models.CharField(max_length=50, verbose_name='bar')),
                ('service_count', models.IntegerField(default=0, verbose_name='service_count')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.driver', verbose_name='driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'WorkShift',
                'verbose_name_plural': 'WorkShifts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Tavaghof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=50, verbose_name='cause')),
                ('duration', models.FloatField(default=1, verbose_name='duration')),
                ('descriptin', models.CharField(blank=True, max_length=50, null=True, verbose_name='descriptin')),
                ('vehicle_hour', models.FloatField(default=0, verbose_name='vehicle_hour')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.workshift', verbose_name='workshift')),
            ],
            options={
                'verbose_name': 'Tavaghof',
                'verbose_name_plural': 'Tavaghofs',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='product')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.IntegerField(default=0, verbose_name='unit_price')),
                ('anbar', models.CharField(max_length=50, verbose_name='anbar')),
                ('service_man', models.CharField(max_length=50, verbose_name='service_man')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.workshift', verbose_name='workshift')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='OilService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_type', models.CharField(max_length=50, verbose_name='oil_type')),
                ('oil_action', models.CharField(max_length=50, verbose_name='oil_action')),
                ('oil_liter', models.FloatField(default=1, verbose_name='oil_liter')),
                ('vehicle_hour', models.FloatField(default=0, verbose_name='vehicle_hour')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.workshift', verbose_name='workshift')),
            ],
            options={
                'verbose_name': 'OilService',
                'verbose_name_plural': 'OilServices',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='FilterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('فیلتر روغن', 'فیلتر روغن'), ('فیلتر هوا', 'فیلتر هوا'), ('فیلتر گازوئیل', 'فیلتر گازوئیل'), ('فیلتر هیدرولیک', 'فیلتر هیدرولیک'), ('فیلتر نانو', 'فیلتر نانو'), ('فیلتر آبگیر', 'فیلتر آبگیر'), ('فیلتر تانک', 'فیلتر تانک'), ('فیلتر بخارکش', 'فیلتر بخارکش'), ('فیلتر مغناطیسی', 'فیلتر مغناطیسی'), ('فیلتر داخلی', 'فیلتر داخلی'), ('فیلتر بیرونی', 'فیلتر بیرونی'), ('فیلتر کابین', 'فیلتر کابین'), ('فیلتر سلکتور', 'فیلتر سلکتور')], max_length=50, verbose_name='filter type')),
                ('filter_action', models.CharField(choices=[('تعویض', 'تعویض'), ('بادگیری', 'بادگیری')], max_length=50, verbose_name='filter action')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.workshift', verbose_name='workshift')),
            ],
            options={
                'verbose_name': 'FilterService',
                'verbose_name_plural': 'FilterServices',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
