# Generated by Django 5.2.6 on 2026-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_alter_area_page'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatus',
            name='images',
            field=models.ManyToManyField(blank=True, to='attachments.image', verbose_name='images'),
        ),
    ]
