# Generated by Django 5.2.6 on 2026-09-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_asset_owner'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='بی نام', max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='driver_code'),
        ),
        migrations.AddField(
            model_name='driver',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='license_no'),
        ),
        migrations.AddField(
            model_name='driver',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='serviceman',
            name='full_name',
            field=models.CharField(default='بی نام', max_length=50, verbose_name='full_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سایز وسیله '),
        ),
        migrations.AlterField(
            model_name='driver',
            name='person_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account'),
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='person_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.personaccount', verbose_name='person_account'),
        ),
    ]
