# Generated by Django 5.2.6 on 2026-08-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='qq', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
