# Generated by Django 5.2.6 on 2026-09-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سایز وسیله '),
        ),
    ]
