# Generated by Django 5.2.6 on 2026-08-14 14:02

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_productspecification_parent'),
        ('core', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='project_name')),
                ('area_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='area_name')),
            ],
            options={
                'verbose_name': 'VehicleEvent',
                'verbose_name_plural': 'VehicleEvents',
            },
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='OilingMaintenance',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.maintenance')),
                ('oil_type', models.CharField(choices=[('15 W 40', '15 W 40'), ('20 W 40', '20 W 40'), ('25 W 40', '25 W 40')], max_length=50, verbose_name='oil type')),
                ('oil_liter', models.FloatField(verbose_name='oil liter')),
                ('fuel_liter', models.FloatField(verbose_name='fuel liter')),
                ('replace_oil', models.BooleanField(verbose_name='replace oil')),
                ('over_load_oil', models.BooleanField(verbose_name='over load oil')),
            ],
            options={
                'verbose_name': 'OilingMaintenance',
                'verbose_name_plural': 'OilingMaintenances',
            },
            bases=('transport.maintenance',),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='hour'),
        ),
        migrations.AddField(
            model_name='maintenanceinvoice',
            name='hour',
            field=models.IntegerField(default=0, verbose_name='hour'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد وسیله '),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('لودر', 'لودر'), ('بیل مکانیکی', 'بیل مکانیکی'), ('کمپرسی', 'کمپرسی'), ('گریدر', 'گریدر'), ('بلدوزر', 'بلدوزر'), ('تریلی', 'تریلی'), ('خاور', 'خاور'), ('وانت', 'وانت'), ('سواری', 'سواری'), ('موتورسیکلت', 'موتورسیکلت'), ('اتوبوس', 'اتوبوس'), ('تاکسی', 'تاکسی'), ('کانتینر', 'کانتینر'), ('سپراتور', 'سپراتور')], default='سواری', max_length=50, verbose_name='نوع وسیله '),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.personaccount', verbose_name='person_account')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transport.driver', verbose_name='driver'),
        ),
        migrations.CreateModel(
            name='Karkerd',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicleevent')),
                ('start_hour', models.FloatField(verbose_name='ساعت شروع')),
                ('end_hour', models.FloatField(verbose_name='ساعت پایان')),
                ('start_kilometer', models.FloatField(blank=True, null=True, verbose_name='کیلومتر شروع')),
                ('end_kilometer', models.FloatField(blank=True, null=True, verbose_name='کیلومتر پایان')),
                ('load', models.CharField(blank=True, max_length=50, null=True, verbose_name='load')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
            ],
            options={
                'verbose_name': 'Karkerd',
                'verbose_name_plural': 'Karkerds',
            },
            bases=('transport.vehicleevent',),
        ),
        migrations.CreateModel(
            name='Tavaghof',
            fields=[
                ('vehicleevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transport.vehicleevent')),
                ('cause', models.CharField(max_length=50, verbose_name='علت')),
            ],
            options={
                'verbose_name': 'Tavaghof',
                'verbose_name_plural': 'Tavaghofs',
            },
            bases=('transport.vehicleevent',),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver', verbose_name='driver'),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle'),
        ),
        migrations.CreateModel(
            name='OilingMaintenanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('فیلتر روغن', 'فیلتر روغن'), ('فیلتر گازوئیل', 'فیلتر گازوئیل'), ('فیلتر هیدرولیک', 'فیلتر هیدرولیک'), ('فیلتر نانو', 'فیلتر نانو'), ('فیلتر آبگیر', 'فیلتر آبگیر'), ('فیلتر تانک', 'فیلتر تانک'), ('فیلتر بخارکش', 'فیلتر بخارکش'), ('فیلتر مغناطیسی', 'فیلتر مغناطیسی'), ('فیلتر داخلی', 'فیلتر داخلی'), ('فیلتر بیرونی', 'فیلتر بیرونی'), ('فیلتر کابین', 'فیلتر کابین'), ('فیلتر سلکتور', 'فیلتر سلکتور')], max_length=50, verbose_name='filter type')),
                ('filter_action', models.CharField(choices=[('تعویض', 'تعویض'), ('بادگیری', 'بادگیری')], max_length=50, verbose_name='filter action')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('cost', models.IntegerField(default=0, verbose_name='cost')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('oiling_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.oilingmaintenance', verbose_name='oiling_maintenance')),
            ],
            options={
                'verbose_name': 'OilingMaintenanceDetail',
                'verbose_name_plural': 'OilingMaintenanceDetails',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
    ]
