# Generated by Django 5.2.6 on 2026-08-15 09:23

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
        ('transport', '0002_vehicleevent_oilingmaintenance_maintenance_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_datetime', models.DateTimeField(verbose_name='status_datetime')),
                ('motor', models.CharField(blank=True, max_length=500, null=True, verbose_name='motor')),
                ('gear_box', models.CharField(blank=True, max_length=500, null=True, verbose_name='gear_box')),
                ('ziroband', models.CharField(blank=True, max_length=500, null=True, verbose_name='ziroband')),
                ('cabin', models.CharField(blank=True, max_length=500, null=True, verbose_name='cabin')),
                ('cooler', models.CharField(blank=True, max_length=500, null=True, verbose_name='cooler')),
                ('heater', models.CharField(blank=True, max_length=500, null=True, verbose_name='heater')),
                ('wiring', models.CharField(blank=True, max_length=500, null=True, verbose_name='wiring')),
                ('light', models.CharField(blank=True, max_length=500, null=True, verbose_name='light')),
                ('hydrolic', models.CharField(blank=True, max_length=500, null=True, verbose_name='hydrolic')),
                ('pakat', models.CharField(blank=True, max_length=500, null=True, verbose_name='pakat')),
                ('compress', models.CharField(blank=True, max_length=500, null=True, verbose_name='compress')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='توضیحات کامل')),
                ('locaion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.location', verbose_name='location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'VehicleStatus',
                'verbose_name_plural': 'VehicleStatuss',
            },
        ),
    ]
