# Generated by Django 5.2.17 on 2026-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_vehiclestatus_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gasoil_liter',
            field=models.FloatField(default=0, verbose_name='gasoil_liter'),
        ),
    ]
