# Generated by Django 5.2.6 on 2026-08-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_product_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='gasoil_liter',
            field=models.IntegerField(default=0, verbose_name='gasoil_liter'),
        ),
    ]
