# Generated by Django 5.2.6 on 2026-08-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_vehiclestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclestatus',
            options={'verbose_name': 'VehicleStatus', 'verbose_name_plural': 'VehicleStatuses'},
        ),
        migrations.AddField(
            model_name='vehiclestatus',
            name='hour',
            field=models.IntegerField(default=1, verbose_name='hour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestatus',
            name='kilometer',
            field=models.IntegerField(default=1, verbose_name='kilometer'),
            preserve_default=False,
        ),
    ]
