# Generated by Django 5.2.17 on 2026-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_service_gasoil_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilservice',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='cost'),
        ),
    ]
