# Generated by Django 5.2.6 on 2026-08-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_workshift_gasoil_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilservice',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='cost'),
        ),
        migrations.AddField(
            model_name='oilservice',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
    ]
