# Generated by Django 5.2.6 on 2026-08-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_vehiclestatus_options_vehiclestatus_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleevent',
            name='vehicle_event_type',
            field=models.CharField(default='توقف', max_length=50, verbose_name='vehicle_event_type'),
            preserve_default=False,
        ),
    ]
