# Generated by Django 5.2.6 on 2026-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_oilservice_cost_oilservice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='service_count',
        ),
        migrations.AddField(
            model_name='workshift',
            name='bar_count',
            field=models.IntegerField(default=0, verbose_name='bar_count'),
        ),
    ]
