# Generated by Django 5.2.6 on 2026-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_vehicleevent_vehicle_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karkerd',
            name='end_kilometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='کیلومتر پایان'),
        ),
        migrations.AlterField(
            model_name='karkerd',
            name='start_kilometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='کیلومتر شروع'),
        ),
    ]
