# Generated by Django 5.2.6 on 2026-08-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_productanbar_service_delete_karkerd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAnbar',
            new_name='AnbarProduct',
        ),
        migrations.AlterModelOptions(
            name='anbarproduct',
            options={'verbose_name': 'AnbarProduct', 'verbose_name_plural': 'AnbarProducts'},
        ),
    ]
