# Generated by Django 5.2.6 on 2026-08-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_karkerd_end_kilometer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclestatus',
            old_name='locaion',
            new_name='location',
        ),
    ]
