# Generated by Django 5.2.6 on 2026-08-27 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_rename_productanbar_anbarproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarproduct',
            name='shift',
            field=models.CharField(default='asas', max_length=50, verbose_name='shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anbarproduct',
            name='shift_date',
            field=models.DateField(default=datetime.datetime(2026, 8, 27, 11, 7, 9, 420969, tzinfo=datetime.timezone.utc), verbose_name='shift_date'),
            preserve_default=False,
        ),
    ]
