# Generated by Django 5.2.6 on 2026-08-23 23:00

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_rename_locaion_vehiclestatus_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilingmaintenancedetail',
            name='oiling_maintenance',
        ),
        migrations.AlterField(
            model_name='oilingmaintenance',
            name='oil_type',
            field=models.CharField(choices=[('15 W 40', '15 W 40'), ('20 W 40', '20 W 40'), ('25 W 40', '25 W 40'), ('20 W 50', '20 W 50')], max_length=50, verbose_name='oil type'),
        ),
        migrations.AlterField(
            model_name='oilingmaintenancedetail',
            name='filter_type',
            field=models.CharField(choices=[('فیلتر روغن', 'فیلتر روغن'), ('فیلتر هوا', 'فیلتر هوا'), ('فیلتر گازوئیل', 'فیلتر گازوئیل'), ('فیلتر هیدرولیک', 'فیلتر هیدرولیک'), ('فیلتر نانو', 'فیلتر نانو'), ('فیلتر آبگیر', 'فیلتر آبگیر'), ('فیلتر تانک', 'فیلتر تانک'), ('فیلتر بخارکش', 'فیلتر بخارکش'), ('فیلتر مغناطیسی', 'فیلتر مغناطیسی'), ('فیلتر داخلی', 'فیلتر داخلی'), ('فیلتر بیرونی', 'فیلتر بیرونی'), ('فیلتر کابین', 'فیلتر کابین'), ('فیلتر سلکتور', 'فیلتر سلکتور')], max_length=50, verbose_name='filter type'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='shift_date')),
                ('shift', models.CharField(max_length=50, verbose_name='shift')),
                ('start_hour', models.IntegerField(default=0, verbose_name='start_hour')),
                ('end_hour', models.IntegerField(default=0, verbose_name='end_hour')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('oil_type', models.CharField(max_length=50, verbose_name='oil_type')),
                ('oil_liter', models.IntegerField(default=0, verbose_name='oil_liter')),
                ('gasoil_liter', models.IntegerField(default=0, verbose_name='gasoil_liter')),
                ('vehicle_hour', models.IntegerField(default=0, verbose_name='vehicle_hour')),
                ('oil_service', models.CharField(max_length=50, verbose_name='oil_service')),
                ('tavaghof_cause', models.CharField(blank=True, max_length=50, null=True, verbose_name='tavaghof_cause')),
                ('tavaghof_duration', models.IntegerField(default=0, verbose_name='tavaghof_duration')),
                ('tavaghof_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='tavaghof_description')),
                ('kharabi_duration', models.IntegerField(default=0, verbose_name='kharabi_duration')),
                ('kharabi_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='kharabi_description')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.driver', verbose_name='driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'WorkShift',
                'verbose_name_plural': 'WorkShifts',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.AddField(
            model_name='oilingmaintenancedetail',
            name='work_shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.workshift', verbose_name='oiling_maintenance'),
            preserve_default=False,
        ),
    ]
