# Generated by Django 5.2.6 on 2026-08-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_anbarproduct_shift_anbarproduct_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع وسیله '),
        ),
    ]
