# Generated by Django 5.2.6 on 2026-08-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_vehicle_brand_name_alter_vehicle_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatus',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
    ]
