# Generated by Django 5.2.6 on 2026-06-04 16:23

import django.db.models.deletion
import utility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.page')),
                ('shops', models.ManyToManyField(blank=True, to='market.shop', verbose_name='shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
            bases=('core.page',),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('table_no', models.IntegerField(default=0, verbose_name='شماره میز')),
                ('code', models.CharField(max_length=500, verbose_name='code')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
            bases=(models.Model, utility.models.LinkHelper),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('cartitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.cartitem')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
            },
            bases=('market.cartitem',),
        ),
        migrations.CreateModel(
            name='TableCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'TableCustomer',
                'verbose_name_plural': 'TableCustomers',
            },
            bases=('market.customer',),
        ),
    ]
