# Generated by Django 5.2.6 on 2026-06-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_asset_price'),
        ('cafe', '0001_initial'),
        ('core', '0001_initial'),
        ('market', '0001_initial'),
        ('organization', '0002_alter_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.employee')),
            ],
            options={
                'verbose_name': 'Barista',
                'verbose_name_plural': 'Baristas',
            },
            bases=('organization.employee',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('در حال استقرار', 'در حال استقرار'), ('در حال پذیرایی', 'در حال پذیرایی'), ('اتمام یافته', 'اتمام یافته'), ('در حال انتخاب', 'در حال انتخاب'), ('در انتظار سرویس', 'در انتظار سرویس'), ('آزاد', 'آزاد')], max_length=50, verbose_name='status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='customer')),
                ('invoices', models.ManyToManyField(blank=True, to='accounting.invoice', verbose_name='invoices')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'OrderLog',
                'verbose_name_plural': 'OrderLogs',
            },
            bases=('core.event',),
        ),
    ]
